### ISSUE TITLE
[BUG] Minor Search bar CSS issue

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#148]
In the browser console, I am getting Expected declaration but found ‘&’.  Skipped to next declaration. [localhost:3000:19:5](http://localhost:3000/)
Elements matching selector: .search-input
NodeList [ input.search-input
]
​
0: <input class="search-input " type="text" placeholder="Search..." value="Python">

I couldn't figure out where the `&` was located, easily but it actually may be describing this portion of BookSearch.css:

```css
.search-input {
    width: 300px;
    padding: 0.563rem;
    font-size: 0.875rem;
    border: none;
    border-radius: 0.5rem;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    margin-right: 10px;
    letter-spacing: 0.5px;

    &:focus,
    &:active,
    &:hover {
        box-shadow: 2px 4px 16px rgba(28, 32, 36, 0.6);
    }
}
```

I am not certain how to fix this, but it's a minor issue.
